# This workflow will do a clean installation of node dependencies, cache/restore them, and run the linter on all source code files

name: ESLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x, 20.x, 21.x]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install Node.js dependencies
        run: |
          npm ci
      - name: Run ESLint
        run: npm run lint
